epimetheus_mssql:
  target: prd
  outputs:
    prd:
      type: sqlserver
      driver: "ODBC Driver 18 for SQL Server"
      server: epimetheusprd.database.windows.net
      database: epimetheusprd
      port: 1433
      schema: epi
      authentication: ServicePrincipal
      tenant_id: "{{ env_var('AZURE_TENANT_ID') }}"
      client_id: "{{ env_var('AZURE_CLIENT_ID') }}"
      client_secret: "{{ env_var('AZURE_CLIENT_SECRET') }}"
