version: 2

models:
  - name: fct_check
    description: ""
    columns:
      - name: daily_check_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: daily_check
        description: ""
        tests:
          - not_null
      - name: caerus_id
        description: ""
        tests:
          - unique
          - not_null
      - name: record_id
        description: ""
        tests:
          - unique
          - not_null
      - name: _ts
        description: ""
        tests:
          - not_null
      - name: _write_date
        description: ""
        tests:
          - not_null
          
  - name: dim_check
    description: ""
    columns:
      - name: check_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: fct_record
    description: ""
    columns:
      - name: record_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: fct_xml
    description: ""
    columns:
      - name: xml_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
