version: 2

models:
  - name: fact_check
    description: ""
    columns:
      - name: daily_check
        description: "The primary key for this table"
        tests:
          - not_null
      - name: caerus_id
        description: ""
        tests:
          - unique
          - not_null
      - name: record_id
        description: ""
        tests:
          - unique
          - not_null
      - name: _ts
        description: ""
        tests:
          - not_null
      - name: _date
        description: ""
        tests:
          - not_null
  - name: dim_check
    description: ""
    columns:
      - name: daily_check
        description: "The primary key for this table"
        tests:
          - not_null
      # - name: transaction_time
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: nr_of_records
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: record_id
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: table
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: zip_name
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: time_generated
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: computer
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: audit_serial_number
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: audit_rule
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: operation
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: filename
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: username
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: exec
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: ftp_time
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: norm_a
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: norm_b
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: e2e_time
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
