version: 2

models:
  - name: fct_check
    description: ""
    columns:
      - name: daily_check_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_check
    description: ""
    columns:
      - name: daily_check_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: fct_record
    description: ""
    columns:
      - name: record_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: fct_xml
    description: ""
    columns:
      - name: xml_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: fct_zip
    description: ""
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('dim_zip')
    columns:
      - name: zip_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
