version: 2

models:
  - name: fct_check
    description: ""
    columns:
      - name: daily_check_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: daily_check
        description: ""
        tests:
          - not_null
      - name: concerned_date
        description: ""
        tests:
          - not_null
      - name: nr_of_violations
        description: ""
      - name: _write_ts
        description: ""
        tests:
          - not_null
      - name: _write_date
        description: ""
        tests:
          - not_null

  - name: dim_check
    description: ""
    columns:
      - name: daily_check_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: daily_check
        description: ""
        tests:
          - not_null
      - name: _write_ts
        description: ""
        tests:
          - not_null
      - name: _write_date
        description: ""
        tests:
          - not_null

  - name: fct_record
    description: ""
    columns:
      - name: record_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: record
        description: ""
        tests:
          - not_null
      - name: table_name
        description: ""
        tests:
          - not_null
      - name: transaction_dt
        description: ""
        tests:
          - not_null
      - name: extraction_dt
        description: ""
        tests:
          - not_null
      - name: write_dt
        description: ""
        tests:
          - not_null
      - name: _write_ts
        description: ""
        tests:
          - not_null
      - name: _write_date
        description: ""
        tests:
          - not_null

  - name: fct_xml
    description: ""
    columns:
      - name: xml_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: xml
        description: ""
        tests:
          - not_null
      - name: table_name
        description: ""
        tests:
          - not_null
      - name: nr_of_records
        description: ""
        tests:
          - not_null
      - name: extraction_dt
        description: ""
        tests:
          - not_null
      - name: _write_ts
        description: ""
        tests:
          - not_null
      - name: _write_date
        description: ""
        tests:
          - not_null

  - name: fct_zip
    description: ""
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('dim_zip')
    columns:
      - name: zip_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: date
        description: ""
        tests:
          - not_null
      - name: number_of_records
        description: ""
        tests:
          - not_null
      - name: datasafe_id
        description: ""
        tests:
          - not_null
      - name: earliest_timestamp
        description: ""
        tests:
          - not_null
      - name: latest_timestamp
        description: ""
        tests:
          - not_null
      - name: generation_date
        description: ""
        tests:
          - not_null
      - name: file_size_uncompressed
        description: ""
        tests:
          - not_null
      - name: file_size_compressed
        description: ""
        tests:
          - not_null
      - name: blob_name
        description: ""
        tests:
          - not_null
      - name: filename
        description: ""
        tests:
          - not_null
      - name: creation_time_adls
        description: ""
        tests:
          - not_null
      - name: _ts
        description: ""
        tests:
          - not_null
