version: 2

models:
  - name: correctness_check
    description: ""
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: sampled_record
    description: ""
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: sent_xml
    description: ""
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null


