version: 2

models:
  - name: xml_files_silver
    description: ""
    columns:
      # - name: _c0
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      - name: xml_name
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      # - name: extraction_time
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: transaction_time
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: nr_of_records
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: record_id
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: table
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: zip_name
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: time_generated
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: computer
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: audit_serial_number
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: audit_rule
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: operation
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: filename
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: username
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: exec
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: ftp_time
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: norm_a
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: norm_b
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
      # - name: e2e_time
      #   description: "The primary key for this table"
      #   tests:
      #     - unique
      #     - not_null
